baseURL = "https://arzedlab.github.io"
languageCode = "en-us"
title = "Arzedlab ğŸªµ"
theme="archie"
copyright = "Â© Ravshan"
pygmentsstyle = "dracula"
#pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	subtitle = "Iâ€™m a cybersecurity researcher at ONESEC focused on low-level systems, firmware, and compilers. I publish technical writeups, run hands-on workshops, and mentor students to help grow the next generation of security researchers. Outside work I enjoy cycling and community outreach."
	avatar = "images/profile.jpg"
	#mathjax = true # enable MathJax support
	#katex = true # enable KaTeX support

[params.meta]
	favicon = true



[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/arzedlab/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/ravshan-rikhsiev/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/arzedlab/"

[[menu.main]]
name = "ğŸ  Home"
url = "/"
weight = 1

[[menu.main]]
name = "ğŸ—‚ï¸ All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "ğŸ’¡ About Me"
url = "/about"
weight = 3

[[menu.main]]
name = "ğŸ“‘ Publications"
url = "/papers"
weight = 4

[[menu.main]]
name = "ğŸ·ï¸ Tags"
url = "/tags"
weight = 5




[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

