baseURL = "https://arzedlab.github.io"
languageCode = "en-us"
title = "Arzedlab ðŸªµ"
theme="archie"
copyright = "Â© Ravshan"
pygmentsstyle = "dracula"
#pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	subtitle = "My name is Ravshan, I am deeply involved in cybersecurity and researching, I will share my knowladge in my blog, here, Welcome..."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/arzedlab/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/arzedlab/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Publications"
url = "/papers"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5




[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

